services:
  - type: web
    name: yify-telegram-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
